language: node_js
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- -- version 0.23.2
  - export PATH="$HOME/.yarn/bin:$PATH"
node_js:
  - '10'
before_script:
  - rm -rf _site
  - yarn run bootstrap
script:
  - yarn run lint
  - yarn run icons:test
  - yarn run icons:generate
  - yarn run icons:build
branches:
  only:
    - master
    - dev
    - /^greenkeeper/.*$/
